name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            build_cmd: npm run build:mac
          - os: ubuntu-latest
            build_cmd: npm run build:linux
          - os: windows-latest
            build_cmd: npm run build:win
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    # macOS code signing setup (same as build workflow)
    - name: Setup macOS Code Signing
      if: matrix.os == 'macos-latest'
      env:
        APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
      run: |
        # Create temp directory for certificates
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        API_KEY_PATH=$RUNNER_TEMP/api_key.p8
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        
        # Decode certificates from secrets
        echo "$APPLE_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
        echo "$APPLE_API_KEY_BASE64" | base64 --decode > $API_KEY_PATH
        
        # Create temporary keychain
        security create-keychain -p "runner" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "runner" $KEYCHAIN_PATH
        
        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "$APPLE_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
        # Allow codesign to use the certificate
        security set-key-partition-list -S apple-tool:,apple: -s -k "runner" $KEYCHAIN_PATH
        
        # Export API key path for electron-builder (uses APPLE_API_KEY)
        echo "APPLE_API_KEY=$API_KEY_PATH" >> $GITHUB_ENV
        
    - name: Build Application
      run: ${{ matrix.build_cmd }} -- --publish always
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # Enable signing only for macOS
        CSC_IDENTITY_AUTO_DISCOVERY: ${{ matrix.os == 'macos-latest' && 'true' || 'false' }}
        # Certificate password for signing
        CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        # Notarization credentials (electron-builder standard)
        # APPLE_API_KEY is set from the file path in setup step
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        
      
    # Security cleanup
    - name: Cleanup Certificates
      if: always() && matrix.os == 'macos-latest'
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db || true
        rm -f $RUNNER_TEMP/build_certificate.p12
        rm -f $RUNNER_TEMP/api_key.p8